<svelte:head>
    <title>james bradbury | code</title>
</svelte:head>

<h1>code</h1>

<p>This page contains information and any relevant links to code I’ve been involved in making or made myself. Most if not all the code I write is open source, so please inspect the code and ask any questions via my e-mail.</p>
<h2 id="reathon">Reathon</h2>
<p>Reathon is a module for creating REAPER sessions directly in Python through an object-oriented interface. Objects inside the module correspond to hierarchical units within REAPER’s .rpp XML-like format allowing you to very easily map native constructs from Python onto the management and formation of new sessions programatically. I now use this to help inspect results from machine listening and learning often generated by <a href="https://github.com/jamesb93/ftis">FTIS</a>.</p>
<p>Language(s): Python 3.8</p>
<p><a href="https://github.com/jamesb93/reathon">https://github.com/jamesb93/reathon</a></p>

<h2 id="metabow-toolkit">MetaBow Toolkit</h2>
<p>As part of a larger research project I was contracted to produce a set of tools in Max to help composers and experienced technologists perform all sorts of gesture recognition and mapping tasks. This was designed for their currently 'private alpha' MetaBow hardware. </p>
<p>Language(s): Max</p>
<p><a href="https://github.com/jamesb93/metabow-toolkit">https://github.com/jamesb93/metabow-toolkit</a></p>

<h2 id="reacollider">ReaCollider</h2>
<p>ReaCollider is a small set of SuperCollider classes that aid in programatically generating REAPER files client side. This is useful for algorithmic composition or for constructing sessions based on analysis performed in SC, such as with machine listening and learning.</p>
<p>Language(s): sclang</p>
<p><a href="https://github.com/jamesb93/ReaCollider">https://github.com/jamesb93/ReaCollider</a></p>

<h2 id="reacoma">ReaCoMa</h2>
<p>ReaCoMa is set of bindings to <a href="https://www.flucoma.org">FluCoMa’s</a> ‘toolbox 1’ algorithms in REAPER. ReaCoMa brings several segmentation and decomposition algorithms which can be applied to creative deconstruction, manipulation and transformation all within your favourite DAW.</p>
<p>Language(s): Lua</p>
<p><a href="https://www.reacoma.xyz">https://www.reacoma.xyz</a></p>
<p><a href="https://www.github.com/jamesb93/reacoma">https://www.github.com/jamesb93/reacoma</a></p>

<h2 id="python-flucoma">python-flucoma</h2>
<p>These are native-ish bindings for Python 3.8+ of the <a href="https://www.flucoma.org">FluCoMa</a> project’s CLI binaries. The bindings offer a functional programming interface to the algorithms which suits the paradigm of chaining together different processes well.</p>
<p>https://github.com/jamesb93/python-flucoma</p>

<h2 id="mosh">mosh</h2>
<p>mosh is a lightweight command-line tool for converting any format of raw data into audio. Several key parameters are exposed to the user allowing them to influence the encoding of the output, such as the bit-depth, channels and the sampling rate. The application compiles to almost any architecture including Android, iOS and ARM alongside standard OS distributions like MacOS, Windows and Linux. Languages(s): Nim</p>
<p><a href="https://github.com/jamesb93/mosh">https://github.com/jamesb93/mosh</a></p>

<h2 id="framelib">FrameLib</h2>
<p>I am currently responsible for building an automated system to generate Max documentation for Alex Harker’s project “FrameLib”. I have also contributed some objects to the official repository too.</p>
<p>Language(s): C++, Python 3+</p>
<p><a href="https://github.com/jamesb93/FrameLib">https://github.com/jamesb93/FrameLib</a></p>

<h2 id="reascripts">ReaScript(s)</h2>
<p>REAPER’s powerful scripting API allows the user to execute lua, EEL and Python code to create custom actions and interfaces.</p>
<p>Language(s): Lua</p>
<p><a href="https://github.com/jamesb93/REAPER-Scripts">https://github.com/jamesb93/REAPER-Scripts</a></p>

<h2 id="z12-rack-implementation">z12 (Rack implementation)</h2>
<p>Miller Puckette outlines an algorithm for generating stochastic sequences that are maximally uniform in this paper. This repo contains a Rack module that implements this algorithm. The output is somewhat markovian in taste and allows you to create some varied rhythms through an interface for managing patterns probabilistically.</p>
<p>Language(s): C++</p>
<p><a href="https://github.com/jamesb93/z12">https://github.com/jamesb93/z12</a></p>

<style>
    h2 {
        padding-top: 15px;
    }
</style>
